// constants/roles.js
module.exports = {
    ADMIN: 'ADMIN',
    RECEPTIONIST: 'RECEPTIONIST',
    INVENTORY_MANAGER: 'INVENTORY_MANAGER',
    TECHNICIAN_LEADER: 'TECHNICIAN_LEADER',
    TECHNICIAN: 'TECHNICIAN',
    CUSTOMER: 'CUSTOMER'
};